version: 1.0.{build}
image: Visual Studio 2015
install:
- ps: >-
    $installer = "$PSScriptRoot\setup.exe"

    (New-Object System.Net.WebClient).DownloadFile("https://cdn.turbo.run/autoit/autoit-v3-setup.exe", $installer)

    Start-Process -FilePath $installer -ArgumentList "/S" -NoNewWindow -Wait
build_script:
- cmd: >-
    "C:\Program Files (x86)\AutoIt3\SciTE\..\AutoIt3.exe" "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3" /NoStatus /prod /in "%CD%\program.au3"
    
    program.exe
